---
- name: notify discord
  hosts: "{{ hosts }}"
  tasks:
    - name: send discord message
      uri:
        url: "https://discord.com/api/webhooks/1148249881052459058/mUprXnzL5RJMvKp1nXiiRIctPPT5cxATtZcleDW1aSJ3b3odRJVLBQ6z3H7th_C8x74G"
        method: POST
        body_format: json
        body: '{"content": "your-message"}'
        headers:
          Content-Type: application/json
        status_code: 204
      # when: your-condition
